5 add news
D-Nevskiy/StreetsRussia pull request #9
Opened 2024-05-15 17:46 UTC by kaedeMirai

2024-05-15 19:25 UTC, D-Nevskiy requested changes

2024-05-15 19:25 UTC, D-Nevskiy commented on backend/news/models.py
> +class News(models.Model):
1. Смотря фигму ([здесь](https://www.figma.com/design/8baTyr1VPNVPMFqVruDX1e/Хакатон%2FУлицы-Росси%2FДЛЯ-РАЗРАБОТКИ?node-id=124-101&t=DbGKeuTWF9y1RxcS-0) ) вижу что полей _link_, _age_restriction_, _created_at, updated_at_ нет на макете, думаю нужно или договориться о добавлении этих полей на макет или убрать их из нашей модели :) Чтобы потом не было недопониманий
2. Вижу еще на макете, Влада отметила какой-то значок "означающую крутую новость", думаю тоже нужно будет уточнить по этому поводу
3. До этого обсуждали что в мероприятиях будем хранить несколько медиа-файлов, в том числе видео, может для новостей тоже добавить возможность хранения видео? Если согласен, можно добавить мою валидацию для разрешения и размера файлов, будет полезно, чтобы не захламлять S3.

2024-05-15 19:25 UTC, D-Nevskiy commented on backend/news/models.py
> +    name = models.CharField(max_length=LEN_CATEGORY_NAME, unique=True, verbose_name='Наименование')
Здесь переносы оформлены не по PEP8

2024-05-15 19:25 UTC, D-Nevskiy commented on backend/news/models.py
> +    image = models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='Изображение')
А здесь длинная строчка, нужно перенести
Советую запустить проверку flake8, файл с настройками уже лежит в ветке dev.
В дальнейшем всё равно в workflow будет проверка от flake8

2024-05-15 19:25 UTC, D-Nevskiy commented on backend/news/models.py
> +    def __str__(self):
*как-то душно, но всё же* :) 

Выписка из официальной документации Django:
Порядок внутренних классов модели и стандартных методов должен быть следующим (с учетом того, что они не все требуются):

- Все поля базы данных
- Настраиваемые атрибуты менеджера
- class Meta
- def __str__()
- def save()
- def get_absolute_url()
- Любые кастомные методы

2024-05-16 08:22 UTC, kaedeMirai commented on backend/news/models.py
> +class News(models.Model):
1. Удалил ненужные поля: link, age_restriction. Добавил поле city, согласно макетам.(импортнул модель из твоего приложения). created_at, updated_at - это скорее внутренние поля, для фильтрации по дате создания и тд. И чтобы отслеживать создание и изменение объектов в бд. 
3. Узнаем)
4. Добавил похожую модель и твою валидацию.

2024-05-16 08:22 UTC, kaedeMirai commented on backend/news/models.py
> +    name = models.CharField(max_length=LEN_CATEGORY_NAME, unique=True, verbose_name='Наименование')
Поправил

2024-05-16 08:22 UTC, kaedeMirai commented on backend/news/models.py
> +    image = models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='Изображение')
Поправил

2024-05-16 08:23 UTC, kaedeMirai commented on backend/news/models.py
> +    def __str__(self):
Не, хорошие замечания)
Поправил.

2024-05-16 10:43 UTC, D-Nevskiy approved these changes

2024-05-16 10:44 UTC, merged